### ISSUE TITLE
There was a problem downloading datasets using scripts

### ISSUE THREAD

**Issue by HinCold** [billywzh717/N24News#1]
Hello, I accidentally saw the data set n24news. Thank you for your excellent work.I was very interested in this work, but I was disconnected when I tried to download it with this code. It seems to be limited by the website. I can't download it after downloading too often. I'd like to ask if you have any solutions, or whether you can send it through email. Thank you very much.

**Comment by billywzh717** [comment]
You can try to add this header in __main__ function: 
`
hdr = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
        'Accept-Encoding': 'none',
        'Accept-Language': 'en-US,en;q=0.8',
        'Connection': 'keep-alive'}
`
and then add it to **_download_image_** function like this:
`img_data = requests.get(item['image_url'], stream=True, headers=hdr).content`

If this does not work, you can email me, then I can send you a copy of this dataset.

> Hello, I accidentally saw the data set n24news. Thank you for your excellent work.I was very interested in this work, but I was disconnected when I tried to download it with this code. It seems to be limited by the website. I can't download it after downloading too often. I'd like to ask if you have any solutions, or whether you can send it through email. Thank you very much.

**Comment by KobeBryant8-24-MVP** [comment]
Hi, could you please send me The Baidu Cloud link of the copy of the dataset as well? My email address is 
 doitdoitnownownow@gmail.com
Thanks a lot!

**Comment by ZhouHongLiang6** [comment]
Hi, could you please send me The Baidu Cloud link of the copy of the dataset as well? My email address is
mufeng696@gmail.com
Thanks a lot!

**Comment by AristarkhovZakhar** [comment]
Hi, could you please send me The Baidu Cloud link of the copy of the dataset as well? My email address is
[aristarkhov.zakhar-2003@mail.ru](mailto:aristarkhov.zakhar-2003@mail.ru)
Thanks a lot!

**Comment by zhenwangrs** [comment]
> Hi, could you please send me The Baidu Cloud link of the copy of the dataset as well? My email address is [aristarkhov.zakhar-2003@mail.ru](mailto:aristarkhov.zakhar-2003@mail.ru) Thanks a lot!

Hello, the download link is already listed in the readme on GitHub.

**Comment by KobeBryant8-24-MVP** [comment]
where ？where you contact me？



---Original---
From: "Zhen ***@***.***&gt;
Date: Mon, Mar 11, 2024 20:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [billywzh717/N24News] There was a problem downloading datasetsusing scripts (Issue #1)




  
Hi, could you please send me The Baidu Cloud link of the copy of the dataset as well? My email address is ***@***.*** Thanks a lot!
  
Hello, the download link is already listed in the readme on GitHub.
