### ISSUE TITLE
The download is too slow, please ask if there is another way to download, thank you!

### ISSUE THREAD

**Issue by LXXiaogege** [billywzh717/N24News#2]

**Comment by zhenwangrs** [comment]
You can send me an email with your gmail address, then I can send you a copy of this dataset.

**Comment by billywzh717** [comment]
You can send me an email with your gmail address, then I can send you a copy of this dataset.

**Comment by LXXiaogege** [comment]
okAY,lvxin199801@gmail.com  . thank u ,bro

**Comment by LXXiaogege** [comment]
dude, i still can't download the dataset, it's always was reject from website when i  was downloading

**Comment by billywzh717** [comment]
> 

I sent an email to your gmail. You can check it and try the download again. Let me know if there still exists some problems.

**Comment by LXXiaogege** [comment]
yes, i used gmail to download, but it's still have a refuse
the message is : Failure has been banned

**Comment by billywzh717** [comment]
This maybe your own problem since I ask others to test the download from google drive, there is no any issues and the download is fine. Please check the validity of your VPN or google account.

**Comment by LXXiaogege** [comment]
thank your reply. i try it again.

**Comment by LXXiaogege** [comment]
I tried to download the file again, but no matter using Chrome download or other software download will be interrupted, I guess Chrome Drive has permission to deny access, because the file is too large? Can you help me check it, or can you provide other download methods?  appreciate  your help

**Comment by billywzh717** [comment]
There is no downloading issue with google drive since you are not the first one to request this dataset. I will send you a Baidu cloud link later via email. Please check it then.

**Comment by LXXiaogege** [comment]
This problem should be caused by google drive's access token, this file  can not be downloaded within the validity period of the access token, so an error is reported. And it can't be resume.

**Comment by billywzh717** [comment]
The Baidu Cloud link will expire 7 days later. Please download it as soon as possible.

**Comment by MichSc33** [comment]
hey hey is it possible that you can send me the copy of the data set via mail as well? the download is quite slow, thank you a lot and keep going the good work. btw my mail is leeonardo@web.de

**Comment by ljy0ustc** [comment]
Hi, could you please send me the copy of the dataset as well? My email address is joyliao7777@gmail.com. Thanks a lot!

**Comment by KobeBryant8-24-MVP** [comment]
Hi, could you please send me The Baidu Cloud link of the copy of the dataset as well? My email address is doitdoitnownownow@gmail.com 
    Thanks a lot!

**Comment by ZhouHongLiang6** [comment]
Hi, could you please send me the copy of the dataset as well? My email address is mufeng696@gmail.com
Thanks a lot!

**Comment by zhenwangrs** [comment]
> Hi, could you please send me the copy of the dataset as well? My email address is [mufeng696@gmail.com](mailto:mufeng696@gmail.com) Thanks a lot!

@ZhouHongLiang6 I put the Baidu Cloud link in the readme. Please check it.
