### ISSUE TITLE
About the raw dataset 

### ISSUE THREAD

**Issue by Vincent-ZHQ** [billywzh717/N24News#3]
Can you share the raw dataset with me directly? It is a little slow to download one by one. Maybe you can write a code that can download parallelly. 
Thank you very  much, my email is zouhq01@gmail.com

**Comment by Vincent-ZHQ** [comment]
It seems too slow for a one-by-one download. Then I tried to download it parallelly. It will lose connection around 2200th. 
Maybe a one-by-one download could work. But I am not sure.

**Comment by billywzh717** [comment]
The raw data has been sent to you via email. Yes maybe parallelly download is needed. I will try to add it to the code as soon as possible.

**Comment by Vincent-ZHQ** [comment]
I have received your data. Thank you very much.
